version: '3.9'

services:
  db:
    image: postgres:14.2-alpine
    restart: always
    environment:
      - POSTGRES_DB=validador_bootcamps
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=trycatch_tv23
    ports:
      - 5432:5432

  bootcamp-backend:
    build: .
    container_name: bootcamp-backend
    links:
      - db
    depends_on:
      - db
    ports:
      - 3000:3000
