name: Deploy to EC2

on:
  push:
    branches:
      - main # Cambia esto a tu rama deseada

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx (optional for caching)
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t my-app:latest .

      - name: Save Docker image to file
        run: docker save -o my-app.tar my-app:latest

      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v2
        with:
          name: docker-image
          path: my-app.tar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: docker-image
          path: .

      - name: Install SSH client
        run: sudo apt-get install -y sshpass

      - name: Transfer Docker image to EC2
        env:
          SSHPASS: ${{ secrets.EC2_KEY }}
        run: |
          sshpass -e scp -o StrictHostKeyChecking=no my-app.tar ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER }}/my-app.tar

      - name: SSH and deploy
        env:
          SSHPASS: ${{ secrets.EC2_KEY }}
        run: |
          sshpass -e ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/${{ secrets.EC2_USER }}
            ls -l my-app.tar
            docker load -i my-app.tar
            docker stop my-app || true
            docker rm my-app || true
            docker run -d --name my-app -p 80:3000 my-app:latest
          EOF
